version: '3'

services:
  ha-fusion:
    build: .
    container_name: ha-fusion-dev
    ports:
      - "5050:5050"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
      - HASS_URL=http://homeassistant:8123
    restart: always
# cd ~/Developer/ha-fusion && docker-compose -f compose-dev.yml up -d --build ha-fusion
