version: '3'

services:
  ha-fusion:
    image: ghcr.io/symi-daguo/ha-fusion:latest
    container_name: ha-fusion
    ports:
      - "5050:5050"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
      - HASS_URL=http://localhost:8123
    restart: always
